[tool.poetry]
name = "django_test"
version = "0.1.0"
description = ""
authors = ["SaniKyn <gajdukevich.sani@mail.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Django = "~=3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
