# Generated by Django 3.2.14 on 2022-07-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=256)),
                ('hash', models.CharField(max_length=10)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
            ],
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
