# Generated by Django 3.2.14 on 2022-07-12 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Link', '0003_auto_20220710_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmapping',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkmapping',
            name='text',
            field=models.TextField(default='enter'),
            preserve_default=False,
        ),
    ]
